FROM debian:wheezy-slim

RUN set -eux; \
    apt-get update -y; \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        python2.6 \
    ; \
    ln -s /usr/bin/python2.6 /usr/local/bin/python2; \
    ln -s /usr/local/bin/python2 /usr/local/bin/python; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl https://bootstrap.pypa.io/2.6/get-pip.py -o - | PYTHONWARNINGS=ignore python2.6 -
